DoctorOffice/Models/Doctor.cs
using System.Collections.Generic;

namespace DoctorOffice.Models
{
  public class Doctor
  {
    public Doctor()
    {
      this.JoinEntities = new HashSet<DoctorPatient>();
      this.JoinEntities2 = new HashSet<SpecialityDoctor>();
    }
    
    public int DoctorId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<DoctorPatient> JoinEntities { get; set; }
    public virtual ICollection<SpecialityDoctor> JoinEntities2 { get; set; }

  }
}

DoctorOffice/Controllers/DoctorsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using DoctorOffice.Models;
using System.Collections.Generic;
using System.Linq;

namespace DoctorOffice.Controllers
{
  public class DoctorsController : Controller
  {
    private readonly DoctorOfficeContext _db;

    public DoctorsController(DoctorOfficeContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {  
      List<Doctor> thisDoctor = _db.Doctors
        .Include(doctor => doctor.JoinEntities2)
        .ThenInclude(join => join.speciality)
        .ToList();
      return View(thisDoctor);
    }
    public ActionResult Create()
    {
      ViewBag.SpecialityId = new SelectList(_db.Specialities, "SpecialityId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Doctor doctor, int SpecialityId)
    {
      _db.Doctors.Add(doctor);
      _db.SaveChanges();
      if (SpecialityId != 0)
      {
        _db.SpecialityDoctor.Add(new SpecialityDoctor() { SpecialityId = SpecialityId, DoctorId = doctor.DoctorId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      var thisDoctor = _db.Doctors
          .Include(doctor => doctor.JoinEntities)
          .ThenInclude(join => join.patient)
          .FirstOrDefault(doctor => doctor.DoctorId == id);
      return View(thisDoctor);
    } 
    public ActionResult Edit(int id)
    {
      var thisDoctor = _db.Doctors.FirstOrDefault(doctor => doctor.DoctorId == id);
      return View(thisDoctor);
    }

    [HttpPost]
    public ActionResult Edit(Doctor doctor)
    {
      _db.Entry(doctor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisDoctor = _db.Doctors.FirstOrDefault(doctor => doctor.DoctorId == id);
      return View(thisDoctor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisDoctor = _db.Doctors.FirstOrDefault(doctor => doctor.DoctorId == id);
      _db.Doctors.Remove(thisDoctor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddSpeciality(int id)
      {
        ViewBag.SpecialityId = new SelectList(_db.Specialities, "SpecialityId", "Name");
        var thisDoctor = _db.Doctors.FirstOrDefault(doctor => doctor.DoctorId == id);
        return View(thisDoctor);
      }

    [HttpPost]
    public ActionResult AddSpeciality(Doctor doctor, int SpecialityId)
    {
      if (SpecialityId != 0)
      {
        _db.SpecialityDoctor.Add(new SpecialityDoctor() { SpecialityId = SpecialityId, DoctorId = doctor.DoctorId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }
    
    [HttpPost]
    public ActionResult DeleteSpeciality(int joinId)
    {
      var joinEntry = _db.SpecialityDoctor.FirstOrDefault(entry => entry.SpecialityDoctorId == joinId);
      _db.SpecialityDoctor.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }  
}    

DoctorOffice/Views/Doctors/AddSpeciality.cshtml
@{
  Layout = "_Layout";
}

@model DoctorOffice.Models.Doctor

<h2>Add a speciality</h2>

<h4>Add a speciality to this doctor: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.DoctorId)

  @Html.Label("Select speciality")
  @Html.DropDownList("SpecialityId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to doctor", "Index")</p>

DoctorOffice/Views/Doctors/Create.cshtml
@{
  Layout = "_Layout";
}

@model DoctorOffice.Models.Doctor

<div class="home">
  <div class="card border-secondary mb-3 mt-5" style="max-width: 50rem;">
    <div class="card-header"><h1>Add a new doctor</h1></div>
    <div class="card-body">
      @using (Html.BeginForm())
      {
        @Html.LabelFor(model => model.Name, new { @class = "my-2 mx-2" })
        @Html.TextBoxFor(model => model.Name, new { @class = "my-2 mx-2" })
        
        @Html.Label("Select speciality", null, new { @class = "my-2 mx-2" })
        @Html.DropDownList("SpecialityId", null, new { @class = "my-2 mx-2" })

        <button type="submit" class="btn btn-secondary btn-sm my-2 mx-2">Add New Doctor</button>
      }
      <p>@Html.ActionLink("Show all doctors", "Index", new {area = ""}, new { @class = "btn btn-secondary btn-sm my-2 mx-2" })</p>
    </div>
  </div>   
</div>  

DoctorOffice/Views/Doctors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model DoctorOffice.Models.Doctor

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to Doctors", "Index")

DoctorOffice/Views/Doctors/Details.cshtml
@{
  Layout = "_Layout";
}

@model DoctorOffice.Models.Doctor;

<h2 class="mt-4">Doctor Details</h2>
<hr />
<h5>@Html.DisplayNameFor(model => model.Name):</h5> <p>@Html.DisplayFor(model => model.Name)</p>

<h5>Specialities:</h5>
@foreach (var join in Model.JoinEntities2)
  {
    @join.speciality.Name
    @using (Html.BeginForm("DeleteSpeciality", "Doctors"))
      {
        @Html.Hidden("joinId", @join.SpecialityDoctorId)
        <input type="submit" value="Delete" />
      }
  }
      

<hr />
<h5>Patients associated with this doctor:</h5>
@if (@Model.JoinEntities.Count == 0)
{
  <p>This doctor does not have any patients</p>
}
else
{
  <ul>
  @foreach (var join in Model.JoinEntities)
    {
      <li>@join.patient.Name</li>
    }
  </ul>
}

@Html.ActionLink("Add a speciality", "AddSpeciality", new { id = Model.DoctorId }, new { @class = "btn btn-secondary btn-sm ml-2 mt-3" })
@Html.ActionLink("Edit Doctor", "Edit", new { id = Model.DoctorId }, new { @class = "btn btn-secondary btn-sm mx-2 mt-3" })
@Html.ActionLink("Delete Doctor", "Delete", new { id = Model.DoctorId }, new { @class = "btn btn-secondary btn-sm mx-2 mt-3" })

DoctorOffice/Views/Doctors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model DoctorOffice.Models.Doctor

<h2>Edit</h2>

<h4>Edit this doctor: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.DoctorId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

DoctorOffice/Views/Doctors/Index.cshtml
@{
  Layout = "_Layout";
}

@using DoctorOffice.Models;

<h1 class="my-4">Our Doctors</h1>

@* @if (@Model.Count == 0)
{
  <h3>No doctors have been added yet!</h3>
} *@
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Speciality</th>
      <th scope="col">Patient Amount</th>
    </tr>
  </thead>
  <tbody>
    <tr class="table-active">
      @foreach (Doctor doctor in @Model)
      {
        <tr>
        <th>@Html.ActionLink($"{doctor.Name}", "Details", new { id = doctor.DoctorId }, new { @class = "text-black"})</th>
        <th>
          @foreach(var speciality in @doctor.JoinEntities2)
          {
            @speciality.speciality.Name
            <br>
          }
        </th>
        <th>@doctor.JoinEntities.Count()</th>
        </tr> 
      }     
    </tr>
  </tbody>
</table>
</ul>

@Html.ActionLink("Add new Doctor", "Create", new {area = ""}, new { @class = "btn btn-secondary btn-sm my-3 mr-4" })
@Html.ActionLink("Home", "Index", "Home", new {area = ""}, new { @class = "btn btn-secondary btn-sm my-3 mx-4" })