DoctorOffice/Models/Patient.cs
using System.Collections.Generic;

namespace DoctorOffice.Models
{
  public class Patient
  {
    public Patient()
    {
      this.JoinEntities = new HashSet<DoctorPatient>();
    }

    public int PatientId { get; set; }
    public string Name { get; set; }
    public string Birthday { get; set; }
    public string Phone { get; set; }
    public string Address {get; set;}

    public virtual ICollection<DoctorPatient> JoinEntities { get; }
  }
}

DoctorOffice/Controllers/PatientsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using DoctorOffice.Models;
using System.Collections.Generic;
using System.Linq;

namespace DoctorOffice.Controllers
{
  public class PatientsController : Controller
  {
    private readonly DoctorOfficeContext _db;

    public PatientsController(DoctorOfficeContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      return View(_db.Patients.ToList());
    }
    public ActionResult Create()
    {
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Patient patient, int DoctorId)
    {
      _db.Patients.Add(patient);
      _db.SaveChanges();
      if (DoctorId != 0)
      {
        _db.DoctorPatient.Add(new DoctorPatient() { DoctorId = DoctorId, PatientId = patient.PatientId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      var thisPatient = _db.Patients
          .Include(patient => patient.JoinEntities)
          .ThenInclude(join => join.doctor)
          .FirstOrDefault(patient => patient.PatientId == id);
      return View(thisPatient);
    }
    public ActionResult Edit(int id)
    {
      var thisPatient = _db.Patients.FirstOrDefault(patient => patient.PatientId == id);
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "Name");
      return View(thisPatient);
    }

    [HttpPost]
    public ActionResult Edit(Patient patient, int DoctorId)
    {
      if (DoctorId != 0)
      {
        _db.DoctorPatient.Add(new DoctorPatient() { DoctorId = DoctorId, PatientId = patient.PatientId });
      }
      _db.Entry(patient).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisPatient = _db.Patients.FirstOrDefault(patient => patient.PatientId == id);
      return View(thisPatient);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisPatient = _db.Patients.FirstOrDefault(patient => patient.PatientId == id);
      _db.Patients.Remove(thisPatient);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteDoctor(int joinId)
    {
      var joinEntry = _db.DoctorPatient.FirstOrDefault(entry => entry.DoctorPatientId == joinId);
      _db.DoctorPatient.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddDoctor(int id)
    {
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "Name");
      var thisPatient = _db.Patients.FirstOrDefault(patient => patient.PatientId == id);
      return View(thisPatient);
    }

    [HttpPost]
    public ActionResult AddDoctor(Patient patient, int DoctorId)
    {
      if (DoctorId != 0)
      {
        _db.DoctorPatient.Add(new DoctorPatient() { DoctorId = DoctorId, PatientId = patient.PatientId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }
  }
}

DoctorOffice/Views/Patients/AddDoctor.cshtml
@{
  Layout = "_Layout";
}

@model DoctorOffice.Models.Patient

<h2>Add a doctor</h2>

<h4>Add a doctor to this patient: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.PatientId)

  @Html.Label("Select doctor")
  @Html.DropDownList("DoctorId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to doctor", "Index")</p>

DoctorOffice/Views/Patients/Create.cshtml
@{
  Layout = "_Layout";
}

@model DoctorOffice.Models.Patient

<h4>Add a new patient</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.Birthday)
  @Html.TextBoxFor(model => model.Birthday)

  @Html.LabelFor(model => model.Address)
  @Html.TextBoxFor(model => model.Address)

  @Html.LabelFor(model => model.Phone)
  @Html.TextBoxFor(model => model.Phone)


  @Html.Label("Select doctor")
  @Html.DropDownList("DoctorId")

  <input type="submit" value="Add new patient" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all patients", "Index")</p>

DoctorOffice/Views/Patients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model DoctorOffice.Models.Patient

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to Patient", "Index")

DoctorOffice/Views/Patients/Details.cshtml
@{
  Layout = "_Layout";
}

@model DoctorOffice.Models.Patient

<h2>Patient Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@if (@Model.JoinEntities.Count == 0)
{
  <p>This patient does not belong to any doctor</p>
}
else
{
  <h4>Doctor the patient belongs to:</h4>
  <ul>
  @foreach (var join in Model.JoinEntities)
    {
      <li>@join.doctor.Name</li> 
      @using (Html.BeginForm("DeleteDoctor", "Patients"))
      {
        @Html.Hidden("joinId", @join.DoctorPatientId)
        <input type="submit" value="Delete" />
      }
    }
  </ul>
}

<p>@Html.ActionLink("Add a Doctor", "AddDoctor", new { id = Model.PatientId})</p>

<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit Patient", "Edit", new { id = Model.PatientId })</p>
<p>@Html.ActionLink("Delete Patient", "Delete", new { id = Model.PatientId })</p>

DoctorOffice/Views/Patients/Edit.cshtml
@{
  Layout = "_Layout";
}

@model DoctorOffice.Models.Patient

<h2>Edit</h2>

<h4>Edit this patient: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.PatientId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.Birthday)
  @Html.EditorFor(model => model.Birthday)

  @Html.LabelFor(model => model.Address)
  @Html.EditorFor(model => model.Address)

  @Html.LabelFor(model => model.Phone)
  @Html.EditorFor(model => model.Phone)

  @Html.Label("Select Doctor")
  @Html.DropDownList("DoctorId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to patient", "Index")</p>

DoctorOffice/Views/Patients/Index.cshtml
@{
  Layout = "_Layout";
}

@using DoctorOffice.Models;
@model List<DoctorOffice.Models.Patient>;

<h1>Patients</h1>

@if (@Model.Count == 0)
{
  <h3>No patient have been added yet!</h3>
} 

@foreach (Patient patient in Model)
{
  <li>@Html.ActionLink($"{patient.Name}", "Details", new { id = patient.PatientId })</li>
}

<p>@Html.ActionLink("Add new patient", "Create")</p>